import { base, travelers, validate } from './data.js';
const zhFirst = new URLSearchParams(location.search).get('lang')==='zh';
let lang=zhFirst?'zh':'en', selected=0, input={...base}, decision=null, engine=null, model=null, response=null, busy=false, revision=0, engineError=false;
const $=s=>document.querySelector(s), t=(a,b)=>lang==='en'?a:b;
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const statusText={tourist:['Tourist visa','旅游签证'],cultural:['Cultural exchange','文化交流'],diplomatic:['Diplomatic welcome','外交礼遇'],denied:['Entry denied','拒绝入境'],quarantine:['Quarantine hold','隔离检查'],review:['Further review','进一步审核']};
const statusColor=s=>['tourist','cultural','diplomatic'].includes(s)?'approved':s==='denied'?'denied':'hold';
const label=s=>statusText[s]?.[lang==='en'?0:1]||s;
function alien(color){return `<svg viewBox="0 0 220 225" role="img" aria-label="${t('Alien passport portrait','外星人护照肖像')}"><defs><pattern id="grid" width="20" height="20" patternUnits="userSpaceOnUse"><path d="M20 0H0V20" fill="none" stroke="#203e36" stroke-opacity=".12"/></pattern></defs><rect width="220" height="225" rx="4" fill="#e2e7d7"/><rect width="220" height="225" fill="url(#grid)"/><circle cx="110" cy="103" r="72" fill="none" stroke="#8f9a86" stroke-dasharray="3 6"/><path d="M40 225Q42 170 110 170Q178 170 180 225" fill="#254b40"/><path d="M88 157V185Q110 201 132 185V157" fill="${color}"/><path d="M61 65Q110 27 159 65C185 98 150 159 110 177C70 159 35 98 61 65" fill="${color}" stroke="#1e3c31" stroke-width="2"/><ellipse cx="83" cy="105" rx="16" ry="25" transform="rotate(-30 83 105)" fill="#173a31"/><ellipse cx="137" cy="105" rx="16" ry="25" transform="rotate(30 137 105)" fill="#173a31"/><ellipse cx="81" cy="96" rx="5" ry="8" fill="#f5f3df"/><ellipse cx="135" cy="96" rx="5" ry="8" fill="#f5f3df"/><path d="M100 149Q110 154 120 149" stroke="#294e3e" stroke-width="3" fill="none" stroke-linecap="round"/><path d="M94 66L87 32M126 66L134 32" stroke="#1e3c31" stroke-width="3"/><circle cx="86" cy="28" r="7" fill="${color}" stroke="#1e3c31"/><circle cx="135" cy="28" r="7" fill="${color}" stroke="#1e3c31"/><text x="10" y="215" font-family="monospace" font-size="8" fill="#fff">SOL / 003 • VISITOR</text></svg>`;}
function selectField(key,name,options){return `<label class="field"><span>${name}</span><select name="${key}">${options.map(([value,en,zh])=>`<option value="${value}" ${input[key]===value?'selected':''}>${t(en,zh)}</option>`).join('')}</select></label>`;}
function toggle(key,en,zh){return `<label class="toggle"><input type="checkbox" name="${key}" ${input[key]?'checked':''}><span>${t(en,zh)}</span></label>`;}
function render(){
 const p=travelers[selected];document.documentElement.lang=lang==='zh'?'zh-CN':'en';
 $('#app').innerHTML=`<header class="topbar"><a class="wordmark" href="#"><span class="orbit-mark">✳</span> EARTH ENTRY<span class="wordmark-sub">INTERPLANETARY ARRIVALS</span></a><div class="top-right"><span class="station"><i></i> ${t('SOL SYSTEM / GATE 01','太阳系 / 01 号口')}</span><button class="language" id="language" aria-label="${t('Switch to Chinese','切换到英语')}">${t('中文','EN')}</button></div></header>
 <main><section class="hero"><div><p class="eyebrow">${t('DEPARTMENT OF EXTRATERRESTRIAL AFFAIRS','地外事务管理局')} / 001</p><h1>${t('New planet.<br>Same paperwork.','新星球。<br>老规矩。')}</h1><p class="intro">${t('Earth’s first alien immigration desk. You’re on duty.<br>Meet the visitors. Inspect the weird stuff. Stamp a little destiny.','地球第一个外星人入境窗口。今天，你值班。<br>认识来客，检查奇怪行李，为星际旅程盖下一个章。')}</p><div class="hero-note"><span>↳</span> ${t('A playable rules-engine experiment by Daniel Xu','Daniel Xu 的可玩规则引擎实验')}</div></div><div class="planet-art" aria-hidden="true"><span class="star one">✦</span><span class="star two">✧</span><div class="planet"><span></span></div><div class="orbit"></div><span class="planet-caption">YOU ARE HERE ↗<br>EARTH · MOSTLY HARMLESS</span></div></section>
 <section class="queue"><div class="queue-heading"><h2>${t('The arrivals queue','入境队列')}</h2><span>${t('Pick a passport. Every traveler has a story.','选一本护照。每位旅客都有自己的故事。')}</span></div><div class="travelers">${travelers.map((x,i)=>`<button class="traveler ${selected===i?'selected':''}" data-traveler="${i}" ${busy?'disabled':''} aria-pressed="${selected===i}"><span class="mini-alien" style="--alien:${x.color}">◉</span><span><b>${t(x.name,x.zh)}</b><small>${x.role[lang==='en'?0:1]}</small></span><span class="queue-number">0${i+1}</span></button>`).join('')}</div></section>
 <div class="desk"><section class="passport"><div class="section-heading"><span class="eyebrow">01 / ${t('THE PASSPORT','旅客护照')}</span><button id="reset" ${busy?'disabled':''} class="text-button">↺ ${t('Reset traveler','重置旅客')}</button></div><div class="identity"><div class="portrait">${alien(p.color)}</div><div class="identity-copy"><span class="eyebrow">${t('GALACTIC TRAVEL DOCUMENT','银河旅行证件')}</span><h2>${t(p.name,p.zh)}</h2><p class="homeworld">${p.planet} <span>↗</span> Earth</p><blockquote>${p.quote[lang==='en'?0:1]}</blockquote><span class="passport-id">XENO / 000${selected+1} / SOL</span></div></div>
 <form id="manifest"><div class="fields">${selectField('purpose',t('Purpose of visit','访问目的'),[['tourism','Tourism','旅游'],['culture','Cultural exchange','文化交流'],['diplomacy','Diplomatic mission','外交访问']])}${selectField('atmosphere',t('Breathes','呼吸环境'),[['oxygen','Oxygen · Earth-compatible','氧气 · 适配地球'],['methane','Methane','甲烷'],['vacuum','Vacuum · no atmosphere','真空 · 无大气']])}${selectField('cargo',t('Something to declare?','需要申报的行李'),[['none','Just good intentions','只有善意'],['stardust','A jar of stardust','一罐星尘'],['spores','Glowing alien spores','发光外星孢子'],['blackHole','A pocket black hole','一个口袋黑洞']])}<label class="field"><span>${t('Earth days','地球日数')} <output id="days-value">${input.days}</output></span><input type="range" name="days" min="1" max="90" value="${input.days}"></label></div><div class="checklist">${toggle('suit','Atmosphere suit packed','已携带密闭环境服')}${toggle('containment','Biological cargo sealed','生物行李已密封')}${toggle('translator','Translator switched on','翻译器已开启')}${toggle('telepathy','Can read minds','有读心能力')}${toggle('consent','Agrees to ask before reading minds','同意读心前征求许可')}</div><button class="primary" id="inspect" type="submit" ${!decision||busy?'disabled':''}>${busy?t('Inspecting…','正在检查…'):t('Inspect & stamp passport','检查并盖章')} <span>↗</span></button><p class="engine-line" id="engine-state">${engineError?t('Engine could not load. Reload to try again.','引擎加载失败。请刷新重试。'):decision?t('Running locally with GoRules ZEN · no sign-in','GoRules ZEN 本地运行 · 无需登录'):t('Preparing the rules engine…','正在准备规则引擎…')}</p></form></section>
 <section class="decision-panel" aria-labelledby="verdict-title"><div class="section-heading"><span class="eyebrow">02 / ${t('THE DECISION','入境决定')}</span><span class="gate-tag">GATE 01</span></div><div id="decision-content" aria-live="polite">${resultHTML()}</div></section></div>
 <section class="underhood"><div><p class="eyebrow">${t('NO MAGIC. JUST EXPLAINABLE RULES.','没有魔法，只有可解释的规则。')}</p><h2>${t('Behind every stamp, a decision graph.','每一个印章背后，都有决策图。')}</h2><p>${t('One table collects every inspection finding. A second table applies the first matching admission rule. Diplomatic status never skips a safety check.','第一张决策表收集所有检查结果，第二张表按顺序匹配入境规则。外交身份也不能跳过安全检查。')}</p></div><div class="graph"><span>${t('Manifest','申报')}</span><b>→</b><span>${t('Inspect','检查')}<small>COLLECT</small></span><b>→</b><span>${t('Decide','决定')}<small>FIRST</small></span><b>→</b><span>${t('Stamp','盖章')}</span></div><details><summary>${t('Open the rulebook','打开规则手册')} <span>↗</span></summary><div id="rulebook">${rulebookHTML()}</div></details><div class="source-links"><a href="./immigration.json" download>${t('Download decision model ↓','下载决策模型 ↓')}</a><a href="https://github.com/xudaniel/zen-Gorules/tree/master/examples/alien-immigration">${t('Explore the code ↗','查看源代码 ↗')}</a></div></section>
 <footer><span>EARTH ENTRY <span class="footer-star">✳</span> ${t('An imaginary border. A real rules engine.','虚构的边境，真实的规则引擎。')}</span><span>${t('Demo by','演示制作')} <a href="https://github.com/xudaniel">Daniel Xu</a> · ${t('Powered by','引擎来自')} <a href="https://github.com/gorules/zen">GoRules ZEN</a></span><p>${t('Fictional scenario for learning. Nothing is sent to a server; the rules run in your browser.','这是用于学习的虚构场景。规则在浏览器中运行，不向服务器发送申报内容。')}</p></footer></main>`;
 $('#language').onclick=()=>{lang=lang==='en'?'zh':'en';render();};
 document.querySelectorAll('[data-traveler]').forEach(el=>el.onclick=()=>{selected=Number(el.dataset.traveler);input={...travelers[selected].case};response=null;revision++;render();if(decision) inspect();});
 $('#reset').onclick=()=>{input={...p.case};response=null;revision++;render();if(decision) inspect();};
 $('#manifest').oninput=e=>{const key=e.target.name;if(!key)return;input[key]=e.target.type==='checkbox'?e.target.checked:e.target.type==='range'?Number(e.target.value):e.target.value;revision++;response=null;$('#days-value').textContent=input.days;$('#decision-content').innerHTML=resultHTML();$('#rulebook').innerHTML=rulebookHTML();};
 $('#manifest').onsubmit=e=>{e.preventDefault();inspect();};
 bindTrace();
}
function resultHTML(){
 if(!response)return `<div class="empty-verdict"><div class="empty-stamp">✳</div><h2 id="verdict-title">${t('Your stamp awaits.','等待你的印章。')}</h2><p>${t('Change a detail on the passport, then run the inspection to see what Earth has to say.','修改护照上的一项信息，再运行检查，看看地球会如何回应。')}</p><span class="hint">${t('TRY THIS: Can a poet bring a black hole?','试试看：诗人可以带着黑洞入境吗？')}</span></div>`;
 const v=response.result.visa,checks=response.result.checks,passed=statusColor(v.status)==='approved';
 return `<div class="stamp-wrap"><div class="stamp ${statusColor(v.status)}"><span>EARTH ENTRY · SOL SYSTEM</span><strong id="verdict-title">${label(v.status)}</strong><span>${passed?t('CLEARED FOR LANDING','准许登陆'):t('NOT CLEARED FOR LANDING','暂不准许登陆')}</span></div></div><p class="verdict-reason">${esc(v[lang])}</p><div class="receipt"><div><span>${t('Visit length','访问时长')}</span><b>${input.days} ${t('Earth days','地球日')}</b></div><div><span>${t('Matched policy','命中规则')}</span><code>${esc(v.code)}</code></div></div><h3 class="why">${t('Why this decision?','为什么这样决定？')}</h3><ul class="findings">${checks.map(c=>`<li class="${c.severity}"><span class="finding-icon">${c.severity==='info'?'✓':c.severity==='critical'?'×':'!'}</span><span>${esc(c[lang])}</span></li>`).join('')}</ul><div class="challenge"><span>✦</span><p>${passed?t('Try changing the luggage. One tiny black hole can change everything.','试着换一件行李。一个小黑洞，足以改变一切。'):t('Your mission: change the manifest until this traveler can land.','你的任务：调整申报内容，让这位旅客顺利登陆。')}</p></div><details class="trace"><summary>${t('View actual engine trace','查看真实引擎执行记录')}</summary><pre>${esc(JSON.stringify(response.trace,null,2))}</pre><button type="button" class="text-button" id="download-trace">${t('Download trace ↓','下载执行记录 ↓')}</button></details>`;
}
function rulebookHTML(){if(!model)return t('Loading…','加载中…');const table=model.nodes.find(n=>n.id==='admission').content;return `<p>${t('Read top to bottom. The first matching row wins. Blank conditions mean “any value”.','从上往下读取。第一个匹配行生效，空白条件表示任意值。')}</p><div class="rule-scroll"><table><thead><tr><th>#</th><th>${t('Condition','条件')}</th><th>${t('Outcome','结果')}</th></tr></thead><tbody>${table.rules.map((r,i)=>`<tr class="${response?.result.visa.code===r._id?'matched':''}"><td>${i+1}</td><td>${esc(table.inputs.filter(x=>r[x.id]).map(x=>`${x.field} ${r[x.id]}`).join(' AND ')||t('Otherwise','其他情况'))}</td><td>${label(JSON.parse(r.status))}</td></tr>`).join('')}</tbody></table></div>`;}
function bindTrace(){const btn=$('#download-trace');if(btn)btn.onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(response,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='earth-entry-trace.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};}
async function inspect(){if(!decision||busy)return;busy=true;const runRevision=revision;const snapshot={...input};render();try{const result=await decision.evaluate(validate(snapshot),{trace:true});if(runRevision===revision){response=result;}}catch(e){engineError=true;console.error(e);response=null;}finally{busy=false;render();}}
async function init(){try{
 if(!crossOriginIsolated){
  if(!('serviceWorker' in navigator))throw new Error('Cross-origin isolation unavailable');
  await navigator.serviceWorker.register('./isolation-worker.js');await navigator.serviceWorker.ready;
  if(!sessionStorage.getItem('earth-entry-isolation-reload')){sessionStorage.setItem('earth-entry-isolation-reload','1');location.reload();return;}
  throw new Error('This browser does not support the isolation required by ZEN');
 }
 sessionStorage.removeItem('earth-entry-isolation-reload');
 const res=await fetch('./immigration.json');if(!res.ok)throw new Error('Missing model');model=await res.json();
 const {ZenEngine}=await import('@gorules/zen-engine-wasm32-wasi');engine=new ZenEngine();decision=engine.createDecision(model);decision.validate();render();await inspect();
 }catch(e){console.error(e);engineError=true;render();}}
render();init();
