"""Build English presentation assets from the shared Chinese sources and catalog.

Run after changing UI copy or rules. Translations never change request fields,
rule conditions, authorization checks, persisted records, or audit exports.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
CATALOG = json.loads((ROOT / 'locales/en.json').read_text(encoding='utf-8'))
PATTERN = re.compile('|'.join(re.escape(key) for key in sorted(CATALOG, key=len, reverse=True)))


def translate(text):
    return PATTERN.sub(lambda match: CATALOG[match[0]], text)


def translate_json(value):
    if isinstance(value, str):
        return translate(value)
    if isinstance(value, list):
        return [translate_json(item) for item in value]
    if isinstance(value, dict):
        return {key: translate_json(item) for key, item in value.items()}
    return value


def artifacts():
    html = translate((ROOT / 'static/index.html').read_text(encoding='utf-8'))
    html = html.replace('lang="zh-CN"', 'lang="en"').replace('src="/app.js"', 'src="/app.en.js"')
    html = html.replace('href="/en/" lang="en" hreflang="en"', 'href="/" lang="zh-CN" hreflang="zh-CN"').replace('>English</a>', '>中文</a>')
    html = html.replace('href="/" class="brand"', 'href="/en/" class="brand"').replace('class="brand" href="/"', 'class="brand" href="/en/"')
    html = html.replace('agent-approval.json', 'agent-approval.en.json')
    # Keys stay Chinese so API labels/errors can be localized without altering API data.
    prelude = "// Generated by build_english.py; edit shared sources and locales/en.json.\n"
    prelude += 'window.agentGateEnglish=' + json.dumps(CATALOG, ensure_ascii=False) + ';\n'
    prelude += r'''{
 const catalog=window.agentGateEnglish;
 const escapeRE=value=>value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
 const pattern=new RegExp(Object.keys(catalog).sort((a,b)=>b.length-a.length).map(escapeRE).join('|'),'g');
 window.agentGateTranslate=value=>typeof value==='string'?value.replace(pattern,match=>catalog[match]):value;
}
'''
    js = (ROOT / 'static/app.js').read_text(encoding='utf-8')
    # Redaction markers identify the exact stored receipt bytes; keep these match keys unchanged.
    marker_line = next(line for line in js.splitlines() if line.startswith('const receiptPayload='))
    js = translate(js).replace("toLocaleTimeString('zh-CN'", "toLocaleTimeString('en-GB'")
    js = '\n'.join(marker_line if line.startswith('const receiptPayload=') else line for line in js.splitlines()) + '\n'
    values = {ROOT/'static/index.en.html': html, ROOT/'static/app.en.js': prelude + js}
    source = json.loads((ROOT/'rules/agent-approval.json').read_text(encoding='utf-8'))
    values[ROOT/'rules/agent-approval.en.json'] = json.dumps(translate_json(source), ensure_ascii=False, indent=2)+'\n'
    for source in sorted((ROOT/'samples').glob('*.json')):
        if source.stem.endswith('.en'):
            continue
        sample = translate_json(json.loads(source.read_text(encoding='utf-8')))
        sample['facts']['payload_bytes'] = len(sample['request']['payload'].encode('utf-8'))
        sample['facts']['purpose_length'] = len(sample['request']['purpose'])
        values[source.with_name(source.stem+'.en.json')] = json.dumps(sample, ensure_ascii=False, indent=2)+'\n'
    discount = ROOT.parents[1]/'test-data/discount-approval.json'
    values[discount.with_name('discount-approval.en.json')] = json.dumps(translate_json(json.loads(discount.read_text(encoding='utf-8'))), ensure_ascii=False, indent=2)+'\n'
    return values


if __name__ == '__main__':
    for path, content in artifacts().items():
        path.write_text(content, encoding='utf-8')
        print(path.relative_to(ROOT.parents[1]))
